### ISSUE TITLE
[Bug] Multi-touch zoom + drag to one finger drag sometimes does not work

### ISSUE THREAD

**Issue by ammargitham** [Mr-Pine/Zoomables#11]
The bug happens when you are pinch zooming and dragging, and lift one finger and try to continue dragging. The drag does not work. Although, I can't seem to reproduce all the time, but it happens often. I have attached a video of the issue. Happens at the very start and very end of the video.

https://user-images.githubusercontent.com/8017365/227771124-7468e955-9998-4a4a-9ed4-f4ff9e48da0b.mp4

**Comment by Mr-Pine** [comment]
Thanks for reporting! I've identified the issue and will get a fix out as soon as possible (I'll have to figure out how to publish again 🙃)

~~As a workaround you can always lift up the finger that touched the display last ;)~~

**Comment by Mr-Pine** [comment]
Fix is done. I'll see that I'll publish it tomorrow

**Comment by ammargitham** [comment]
Okay, so the original issue seems to be fixed. But if you try to perform multi-touch scale keeping the original finger on screen it should restart scaling. But it does not. So 2 finger scale (works) -> 1 finger pan (works) -> 2 finger scale (does not work). Since this is similar to the original issue, I did not create a new issue for this.

**Comment by Mr-Pine** [comment]
Version 1.2.1 should fix this too and is out now

**Comment by ammargitham** [comment]
Okay, its fixed. But seems like you forgot to remove some logging from the release.

**Comment by Mr-Pine** [comment]
Oops, my bad. Should be removed now
